framework:
    notifier:
        chatter_transports:
            slack: 'slack://%env(SLACK_TOKEN)%@default?channel=%env(SLACK_CHANNEL)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        #texter_transports:
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email', 'chat/slack']
            high: ['email', 'chat/slack']
            medium: ['email', 'chat/slack']
            low: ['email', 'chat/slack']
        admin_recipients:
            - { email: admin@example.com }
