twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
#    paths:
#        'var/generator_test/templates': ~

when@test:
    twig:
        strict_variables: true
